/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package connector;

import com.gargoylesoftware.htmlunit.BrowserVersion;
import com.gargoylesoftware.htmlunit.FailingHttpStatusCodeException;
import com.gargoylesoftware.htmlunit.WebClient;
import com.gargoylesoftware.htmlunit.WebResponse;
import com.gargoylesoftware.htmlunit.html.HtmlElement;
import com.gargoylesoftware.htmlunit.html.HtmlInput;
import com.gargoylesoftware.htmlunit.html.HtmlPage;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author yajnavalkya
 */
public final class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    Connection con;
    WebClient webClient = new WebClient(BrowserVersion.FIREFOX_38); 
    public login() throws IOException, SQLException {
        initComponents();
        loadup();        
    }
    public void loadup() throws IOException{
        try{
            datab();
        }catch(SQLException e){e.printStackTrace();}
        idmodel();
        nettest();
    }
    public void nettest() throws IOException{
        jButton2.setVisible(false);
        netcheck();
        if(netcheck()){
            if(logincheck()){
                jButton1.setVisible(false);
                jButton2.setVisible(true);
                jLabel3.setText("Already Logged in");
            }
                    
        }
        else if(!netcheck()){jLabel3.setText("No Internet Connection");}
    }
    public void datab() throws SQLException{
         try{
            Class.forName("com.mysql.jdbc.Driver");
          con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/broadband?zeroDateTimeBehavior=convertToNull","yajnab","petrol123");
        }
        catch(SQLException | ClassNotFoundException e){
            e.printStackTrace();}
    }
    public void idmodel(){
        Statement stmt;
        ResultSet rs;
        try{
            stmt = con.createStatement();
            try{
                rs = stmt.executeQuery("Select uname from alliance;");
                jComboBox1.addItem("");
                while(rs.next()){
                     jComboBox1.addItem(rs.getString("uname")); 
                }rs.close();stmt.close();
            }catch(SQLException e){e.printStackTrace();}
        }catch(SQLException e){e.printStackTrace();}
    }
    public void Filesent(File File){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Password");

        jButton2.setText("LogOut");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setEditable(true);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public final boolean netcheck(){
        try{
        final HtmlPage currentPage = webClient.getPage("http://10.254.254.17/0/up/");
        }//Load Alliance Broadband Login Page
        catch(IOException | FailingHttpStatusCodeException e){System.out.println("Website Load Failed");return false;}
        return true;
    }
    public boolean logincheck() throws IOException{
        final HtmlPage currentPage = webClient.getPage("http://10.254.254.17/0/up/");
        
        try{
            final  HtmlInput username = (HtmlInput) currentPage.getElementById("password");
            username.setValueAttribute("test");
        }
        catch(Exception e){ return true;
        }
        return false;             
    }
    public WebClient login(WebClient webClient, String uID, String uPasswd) throws Exception
    {
        webClient.getOptions().setJavaScriptEnabled(false);int n=1,k=1;
        final HtmlPage currentPage = webClient.getPage("http://10.254.254.17/0/up/");
            try{
                final  HtmlInput username = (HtmlInput) currentPage.getElementById("username");
                username.setValueAttribute(uID); //Set value for username
                final  HtmlInput password = (HtmlInput) currentPage.getElementById("password"); //Find element called loginpassword for password
                password.setValueAttribute(uPasswd); //Set value for password
            }
            catch(Exception e){jLabel3.setText("Login Error while putting Values");}
            WebResponse response1 = currentPage.getWebResponse();
            String content2 = response1.getContentAsString();
            //System.out.println(content2);
            final HtmlPage page2;
            try{HtmlElement htmlElement = currentPage.getFirstByXPath("//*[@name=\"login\"]");
            HtmlPage src=htmlElement.click();
            if(logincheck()){jLabel3.setText("Logged In");jButton1.setVisible(false);jButton2.setVisible(true);}if(!logincheck()){jLabel3.setText("Please Check ID and Password");jButton1.setVisible(true);jButton2.setVisible(false);}}
            catch(Exception e){
                jLabel3.setText("Couldn't Click");
            }
        
        return webClient;
    }
    public WebClient logout()throws Exception{
                webClient.getOptions().setJavaScriptEnabled(false);
                 final HtmlPage currentPage = webClient.getPage("http://10.254.254.17/0/up/");
                 try{
                     HtmlElement htmlElement = currentPage.getFirstByXPath("//*[@name=\"logout\"]");
                     HtmlPage src = htmlElement.click();
                     jLabel3.setText("Logged out");
                     jButton1.setVisible(true);jButton2.setVisible(false);
                 }
                 catch(Exception e){
                     jLabel3.setText("Couldn't Log Out");
                     jButton1.setVisible(false);jButton2.setVisible(true);
                     
                 }
                 
        return webClient;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     //Initiate a WebClient variable.   
     String uID = jComboBox1.getSelectedItem().toString();
        char[] ucPasswd = jPasswordField1.getPassword();
        String uPasswd = new String(ucPasswd);
     try {
            webClient = login(webClient, uID, uPasswd);
        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println("Error");
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            webClient = logout();
        } catch (Exception ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            //System.out.println("Error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        Statement stmt;
        try {
            stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select passwd from alliance where uname ='"+jComboBox1.getSelectedItem().toString()+"';");
            while(rs.next()){jPasswordField1.setText(rs.getString("passwd"));break;}
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //login lgn = new login();
        //lgn.loadup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {                
                new login().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
